import type { Metadata } from "next";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import { Header } from "@/components/Header";
import { menus } from "@/variables/menus";
import { Footer } from "@/components/Footer";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "AeroShine | Cuci Pesawat premium",
    template: "%s - AeroShine"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={montserrat.className}>
        <Header menus={menus} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
